# This workflow deploys the Bikeshare FastAPI app on a self-hosted EC2 Github Actions runner


name: Bikeshare project - Continuous Deployment


# Only trigger, when the build workflow succeeded i.e. 'Bikeshare project - Continuous Integration & Delivery'
on:

  workflow_run:
    workflows: ["Bikeshare project - Continuous Integration & Delivery"]
    types:
      - completed
  
  workflow_dispatch:


jobs:

  deploy:

    runs-on: self-hosted
    steps:
    - name: Pull Docker Image
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
      run: sudo docker pull $DOCKER_USER/bikeshare-fastapi:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f bikeshare-fastapi-container || true
    - name: Run Docker Container
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
      run: sudo docker run -it -d -p 8001:8001 --name bikeshare-fastapi-container $DOCKER_USER/bikeshare-fastapi:latest
