# This workflow deploys the Titanic FastAPI app on the self-hosted EC2 Github Actions runner


name: Titanic project - Continuous Deployment


# Only trigger, when the build workflow succeeded i.e. Titanic project - Continuous Integration & Delivery
on:

  workflow_run:
    workflows: ["Titanic project - Continuous Integration & Delivery"]
    types:
      - completed
  
  workflow_dispatch:


jobs:

  deploy:

    runs-on: self-hosted
    steps:
    - name: Pull Docker Image
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
      run: sudo docker pull $DOCKER_USER/titanic-fastapi:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f titanic-fastapi-container || true
    - name: Run Docker Container
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
      run: sudo docker run -it -d -p 8001:8001 --name titanic-fastapi-container $DOCKER_USER/titanic-fastapi:latest