# This workflow:
# - trains a model using the Titanic dataset
# - runs tests using the trained model
# - builds a Python wheel package for the trained model
# - creates and uploads a docker image for a FastAPI app that uses the trained model wheel


name: Titanic project - Continuous Integration & Delivery


on:

  push:
    branches: [ "main" ]
    paths:
      - 'assignments/titanic-project/**/*'
      - '.github/workflows/titanic-project-ci.yml'
  
  pull_request:
    branches: [ "main" ]
    paths:
      - 'assignments/titanic-project/**/*'
      - '.github/workflows/titanic-project-ci.yml'
  
  workflow_dispatch:


defaults:

  run:
    working-directory: assignments/titanic-project/


jobs:

  train:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python titanic_model/train_pipeline.py
    - uses: actions/upload-artifact@v4
      with:
        name: my-trained-pipeline
        path: assignments/titanic-project/titanic_model/trained_models/*.pkl
        retention-days: 1

  test:
  
    needs: train
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - uses: actions/download-artifact@v4
      with:
        name: my-trained-pipeline
        path: assignments/titanic-project/titanic_model/trained_models
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest

  build:
  
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - uses: actions/download-artifact@v4
      with:
        name: my-trained-pipeline
        path: assignments/titanic-project/titanic_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v4
      with:
        name: my-build-package
        path: assignments/titanic-project/dist/*.whl
        retention-days: 1

  push-image:
  
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: my-build-package
        path: assignments/titanic-project/titanic_model_api
    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/titanic-fastapi:latest
    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ vars.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/titanic-fastapi
    - name: Logout of Docker hub
      run: docker logout